FROM node:18

WORKDIR /usr/src/app

# Install project dependencies only once (optional)
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy source code (overwritten by volume anyway)
COPY . .

EXPOSE 4210

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4210"]
